name: Build and Push Docker image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
    
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: follin/pereves:latest # заменить

  deploy:
    name: Pull
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to remote server and run container
      uses: appleboy/ssh-action@master
      with:
        host: 82.97.241.16 # Замените на IP вашего удаленного сервера
        username: root      # Замените на ваше имя пользователя
        password: ${{ secrets.PASSWORD_VDS_SERVER_TW}}  # Храните ваш SSH private key в Secrets
        port: 22
        script: |
          docker stop Pereves
          docker rm Pereves
          docker pull follin/pereves:latest
          docker run -d --name Pereves \
          -e TOKEN=${{ secrets.TOKEN_PEREVES}} \
          -e DataBaseCon=${{ secrets.DataBaseCon}}\
          -it follin/pereves:latest \
          restart: always
